apiVersion: v1
kind: Service
metadata:
  name: openconceptlab-api
  labels:
    app: oclapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendport }}
      targetPort: {{ .Values.service.backendport }}
      protocol: TCP
      name: http
  selector:
    app: oclapi
    