apiVersion: v1
kind: Service
metadata:
  name: openconceptlab-api
  labels:
    {{- include "openconceptlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendport }}
      targetPort: {{ .Values.service.backendport }}
      protocol: TCP
      name: http
  selector:
    {{- include "openconceptlab.selectorLabels" . | nindent 4 }}
    