apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-{{ .Release.Name }}
  labels:
    app: flower
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: flower
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: flower-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "bash", "-c" ]
          args: [
            "./start_flower.sh"
          ]

          ports:
            - name: http
              containerPort: {{ .Values.service.flowerPort }}
              protocol: TCP

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
            
          env:
            - name: REDIS_HOST
              value: {{ .Values.app.container.env.redisHost | quote }}

            - name: REDIS_PORT
              value: {{ .Values.app.container.env.redisPort | quote }}
            
            - name: FLOWER_USER
              value: {{ .Values.app.container.env.flowerUser | quote }}

            - name: FLOWER_PASSWORD
              value: {{ .Values.app.container.env.flowerPassword | quote }}