apiVersion: v1
kind: Service
metadata:
  name: flower-service
  labels:
    app: flower
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.flowerPort }}
      targetPort: {{ .Values.service.flowerPort }}
      protocol: TCP
      name: http
  selector:
    app: flower
    